import 'package:flutter/material.dart';
List<Map> symptomsName =[
  {
    "code": 		  "B",
    "name":       "Biegunka"
  },
  {
    "code": 		  "E",
    "name":       "Katar"
  },
  {
    "code": 		  "F",
    "name":       "Drapanie małżowiny usznej"
  },
];

List<Map> symptomTests = [
  {
    "symptom": 		  "B",
    "id":			      1,
    "description": 	"Biegunka",
    "task":			    "",
    "question":     "W jakim wieku jest pacjent?",
    "optionA":      ">12 msc",
    "optionB":		  "<12 msc",
    "optionANode":	"",
    "optionBNode":	"3",
    "result": 		  "",
    "parent": 		  1
  },
  {
    "symptom": 		  "B",
    "id":			      3,
    "description": 	"Biegunka",
    "task":			    "",
    "question":		  "Czy pacjent był odrobaczany?",
    "optionA":		  "Tak",
    "optionB":		  "Nie",
    "optionANode":	"4",
    "optionBNode":	"8",
    "result": 		  "",
    "parent": 		  1,
  },
  {
    "symptom": 		  "B",
    "id":			      4,
    "description": 	"Biegunka",
    "task":			    "",
    "question":	    "Czy wykonano badanie kału przed odrobaczaniem?",
    "optionA":	    "Tak",
    "optionB":	    "Nie",
    "optionANode":	"6",
    "optionBNode":	"5",
    "result": 		  "",
    "parent": 		  3,
  },
  {
    "symptom": 		  "B",
    "id":			      5,
    "description": 	"Biegunka",
    "task":			    "Wykonaj lub zleć badania kału.",
    "question":		  "",
    "optionA":		  "",
    "optionB":		  "",
    "optionANode":	"",
    "optionBNode":	"",
    "result": 		  "",
    "parent": 		  4,
  },

  {
    "symptom": 		  "B",
    "id":			      6,
    "description": 	"Biegunka",
    "task":			    "",
    "question":		  "Czy pacjent był szczepiony przeciwko chorobom zakaźnym?",
    "optionA":		  "Tak",
    "optionB":		  "Nie",
    "optionANode":	"",
    "optionBNode":	"7",
    "result": 		  "",
    "parent": 		  4,
  },
  {
    "symptom": 		  "B",
    "id":			      7,
    "description": 	"Biegunka",
    "task":			    "Wykonaj test przeciwko parwowirozie.",
    "question":		  "",
    "optionA":		  "",
    "optionB":		  "",
    "optionANode":	"",
    "optionBNode":	"",
    "result": 		  "",
    "parent": 		  6,
  },
  {
    "symptom": 		  "B",
    "id":			      8,
    "description": 	"Biegunka",
    "task":			    "Wydaj preparaty na odrobaczenie",
    "question":		  "",
    "optionA":		  "",
    "optionB":		  "",
    "optionANode":	"",
    "optionBNode":	"",
    "result": 		  "",
    "parent": 		  3,
  },
  {
    "symptom": 		  	"E",
    "id":				1,
    "description": 		"Katar",
    "task":			    "",
    "question":     	"W jakim wieku jest pacjent?",
    "optionA":      	">12 msc",
    "optionB":		  	"<12 msc",
    "optionANode":		"2",
    "optionBNode":		"2",
    "result": 		 	"",
    "parent": 		 	1
  },
  {
    "symptom": 		  	"E",
    "id":				2,
    "description": 		"Katar",
    "task":			    "",
    "question":     	"Czy występuje jednocześnie wypływ z oka?",
    "optionA":      	"Tak",
    "optionB":		  	"Nie",
    "optionANode":		"3",
    "optionBNode":		"3",
    "result": 		 	"",
    "parent": 		 	1
  },
  {
    "symptom": 		  	"E",
    "id":				3,
    "description": 		"Katar",
    "task":			    "",
    "question":     	"Czy pacjent był zaszczepiony przeciwko chorobom zakaźnym?",
    "optionA":      	"Tak",
    "optionB":		  	"Nie",
    "optionANode":		"4",
    "optionBNode":		"5",
    "result": 		 	"",
    "parent": 		 	2
  },
  {
    "symptom": 		  	"E",
    "id":				4,
    "description": 		"Katar",
    "task":			    "",
    "question":     	"Czy jest szansa, że pacjent mógł zainhalować substancje toksyczne?",
    "optionA":      	"Tak",
    "optionB":		  	"Nie",
    "optionANode":		"6",
    "optionBNode":		"5",
    "result": 		 	"",
    "parent": 		 	3
  },
  {
    "symptom": 		  	"E",
    "id":				5,
    "description": 		"Katar",
    "task":			    "Najprawdopodobniej twój pacjent cierpi na koci katar. Leczenie uzależnij od stopnia zaawansowania choroby.",
    "question":     	"",
    "optionA":      	"",
    "optionB":		  	"",
    "optionANode":		"",
    "optionBNode":		"",
    "result": 		 	"",
    "parent": 		 	3
  },
  {
    "symptom": 		  	"E",
    "id":				6,
    "description": 		"Katar",
    "task":			    "Dopytaj właściciela z jakimi dokładnie substancjami miał kontakt pacjent i leczenie uzależnij od otrzymanych informacji.",
    "question":     	"",
    "optionA":      	"",
    "optionB":		  	"",
    "optionANode":		"",
    "optionBNode":		"",
    "result": 		 	"",
    "parent": 		 	4
  },
  {
    "symptom": 		  	"F",
    "id":				1,
    "description": 		"Drapanie małżowiny usznej",
    "task":			    "",
    "question":     	"W jakim wieku jest pacjent?",
    "optionA":      	">10 lat",
    "optionB":		  	"<10 lat",
    "optionANode":		"2",
    "optionBNode":		"2",
    "result": 		 	"",
    "parent": 		 	1
  },
  {
    "symptom": 		  	"F",
    "id":				2,
    "description": 		"Drapanie małżowiny usznej",
    "task":			    "",
    "question":     	"Wykonaj badanie otoskopowe. Czy zaobserwowałeś jakieś zmiany?(np. obrzęk kanału słuchowego, ciała obce, obecność wydzieliny)",
    "optionA":      	"Tak",
    "optionB":		  	"Nie",
    "optionANode":		"3",
    "optionBNode":		"4",
    "result": 		 	"",
    "parent": 		 	1
  },
  {
    "symptom": 		  	"F",
    "id":				3,
    "description": 		"Drapanie małżowiny usznej",
    "task":			    "",
    "question":     	"Czy badanie u pacjenta wywołało dyskomfort?",
    "optionA":      	"Tak",
    "optionB":		  	"Nie",
    "optionANode":		"5",
    "optionBNode":		"6",
    "result": 		 	"",
    "parent": 		 	2
  },
  {
    "symptom": 		  	"F",
    "id":				4,
    "description": 		"Drapanie małżowiny usznej",
    "task":			    "",
    "question":     	"Czy błona bębenkowa jest zmieniona? (przerwana, zmacerowana)",
    "optionA":      	"Tak",
    "optionB":		  	"Nie",
    "optionANode":		"7",
    "optionBNode":		"8",
    "result": 		 	"",
    "parent": 		 	2
  },
  {
    "symptom": 		  	"F",
    "id":				5,
    "description": 		"Drapanie małżowiny usznej",
    "task":			    "Najprawdopodobniej jest to ostre zapalenie ucha zewnętrznego. W pierwszej kolejności wykonaj toaletę ucha, a następnie zaordynuj odpowiednie leczenie.",
    "question":     	"",
    "optionA":      	"",
    "optionB":		  	"",
    "optionANode":		"",
    "optionBNode":		"",
    "result": 		 	"",
    "parent": 		 	3
  },
  {
    "symptom": 		  	"F",
    "id":				6,
    "description": 		"Drapanie małżowiny usznej",
    "task":			    "Wykonaj badania laboratoryjne",
    "question":     	"",
    "optionA":      	"",
    "optionB":		  	"",
    "optionANode":		"",
    "optionBNode":		"",
    "result": 		 	"",
    "parent": 		 	3
  },
  {
    "symptom": 		  	"F",
    "id":				7,
    "description": 		"Drapanie małżowiny usznej",
    "task":			    "Zleć dodatkowe badania dotyczące ucha środkowego(rentgen, meringotomia, wymaz, badanie cytologiczne).",
    "question":     	"",
    "optionA":      	"",
    "optionB":		  	"",
    "optionANode":		"",
    "optionBNode":		"",
    "result": 		 	"",
    "parent": 		 	4
  },
  {
    "symptom": 		  	"F",
    "id":				8,
    "description": 		"Drapanie małżowiny usznej",
    "task":			    "Pobierz wymaz na posiew i na badanie cytologiczne w kierunku zapalenia o charakterze przewlekłym.",
    "question":     	"",
    "optionA":      	"",
    "optionB":		  	"",
    "optionANode":		"",
    "optionBNode":		"",
    "result": 		 	"",
    "parent": 		 	4
  }
  // {
  //   "symptom": 		  "C",
  //   "id":			      1,
  //   "description": 	"Zapalenie",
  //   "task":			    "Prześwietl.",
  //   "question":		  "",
  //   "optionA":		  "",
  //   "optionB":		  "",
  //   "optionANode":	"",
  //   "optionBNode":	"",
  //   "result": 		  "",
  //   "parent": 		  1,
  // }
];